sudo: false

language: c

addons:
  apt:
    packages:
    - luarocks

before_install: luarocks install --local luacheck

before_script: /home/travis/.luarocks/bin/luacheck . --no-color -qo "011"
script: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/testing/release.sh | bash

notifications:
  email:
    on_success: never
    on_failure: always
