name: Package addon

on:
  push:
    branches:
      - master
    tags:
      - '*'
    paths-ignore:
      - '.github/**'

env:
  CF_API_KEY: ${{ secrets.CF_API_KEY }}
  WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
  GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout addon
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run luacheck
        uses: BigWigsMods/actions/luacheck@master
        with:
          args: -qo 011

      - uses: BigWigsMods/packager@master
        with:
          args: -S
